---
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/dbo
    username: root
    password: hinode2018
  jpa:
    hibernate.ddl-auto: none
    show_sql: false